<div class="home-page-header">
  <div class="home-page-header__rgba">
    <i class="fa fa-power-off" aria-hidden="true"></i>
    <h1>Bienvenue sur le blog Operator 101</h1>
    <p>
      Ce blog est à destination des développeurs en herbe qui souhaitent bénéficier de tutoriels divers sur le Developpement. Vous pourrez y consulter des articles sur des thématiques spécifiques et échanger via un système de commentaires sur chaque article.
    </p>
  </div>

</div>
