<div class="modal fade" id="commentNumber<?=$value['id']?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Détail du commentaire</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>
          <?=$value['commentContent'];?>
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form method="POST" action="<?= $requestUrl ?>/posts/reportComments">
          <input type="hidden" name="mode" value="unreport" />
          <input type="hidden" name="idComment" value="<?= $value['id'] ?>">
          <input type="hidden" name="target" value="dashboard" />
          <button type="submit" class="btn btn-primary">Réintégrer le commentaire</button>
        </form>
        <form method="POST" action="<?= $requestUrl ?>/posts/reportComments">
          <input type="hidden" name="mode" value="ban" />
          <input type="hidden" name="idComment" value="<?= $value['id'] ?>">
          <input type="hidden" name="target" value="dashboard" />
          <button type="submit" class="btn btn-primary">Confirmer le signalement</button>
        </form>
      </div>
    </div>
  </div>
</div>
