<button type="button" class="btn btn-primary post-modif-button" data-toggle="modal" data-target="#<?= $value['id'] ?>">
  Modifier
</button>

<div class="modal fade" id="<?= $value['id'] ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form class="form-horizontal" action="<?= $requestUrl ?>/posts/newpost/updatepost" method="POST" enctype="multipart/form-data">

            <div class="form-group">
              <label for="inputTitle" class="col-sm-4 control-label">Titre</label>
                <div class="col-sm-10">
                  <input required type="text" name="postTitle" class="form-control" id="inputTitle" value="<?= $value['postTitle']?>">
              </div>
            </div>

            <div class="form-group">
              <label required for="inputResume" class="col-sm-4 control-label">Résumé de l'article</label>
              <div class="col-sm-10">
                <textarea required class="form-control" name="postResume" maxlength="500" id="inputResume"><?= $value['postResume'] ?>
                </textarea>
              </div>
            </div>

            <div class="form-group">
              <label for="inputThumbnail" class="col-sm-4 control-label">Vignette de l'article</label>
              <div class="col-sm-10">
                <input type="file" name="postThumbnail" class="form-control" id="inputThumbnail" />
              </div>
            </div>

            <div class="form-group">
              <label for="Inputcategories" class="col-sm-4 control-label">Catégories</label>
              <div class="col-sm-10">
                <select required name="categories" class="form-control" id="inputCategories">
                  <?php
                  foreach($categories as $catList)
                  {
                    foreach($catList as $innerValue)
                    {
                      echo("<option");
                      if($value['categoryName']==$innerValue)
                      {
                        echo(" selected");
                      }
                      echo(">
                      $innerValue
                      </option>");
                    }
                  }
                  ?>
                </select>
              </div>
            </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-12">
              <textarea required name="postContent" id="myEditor" >
                <?= $value['postContent'] ?>
              </textarea>
            </div>
          </div>

          <input type="hidden" name="id" class="btn btn-resto101" value="<?= $value['id']?>">



      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Modifier</button>
      </form>
      </div>
    </div>
  </div>
</div>
