<section class="content">
  <div class="row">
    <div class="col-md-3">
      <div class="box box-primary">
        <div class="box-body box-profile">
          <img src="<?= $wwwUrl."/".$user['avatarUrl'] ?>" class="profile-user-img img-responsive img-circle" alt="avatar">
          <h3 class="profile-username text-center">
            <?= $user['firstName']." ".$user['lastName'] ?>
          </h3>
          <ul class="list-group list-group-unbordered">
                <li class="list-group-item">
                  <b>Billets publiés</b> <a class="pull-right" href="<?= $requestUrl ?>/posts?redactorId=<?= $user['id'] ?>" class="pull-right"><?= $user['postNumber'] ?></a>
                </li>
                <li class="list-group-item">
                  <b>Commentaires publiés</b> <a class="visible-*-inline-block pull-right">0</a>
                </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a class="nav-link" href="#abonments" data-toggle="tab" role="tab">Gérer mes abonnements</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#profile" data-toggle="tab" role="tab">Profil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#passwd" data-toggle="tab" role="tab">Mot de passe</a>
          </li>
        </ul>


        <div class="tab-content">
          <div class="tab-pane" id="abonments" role="tabpanel">
            <?php
            // if (isset($order))
            // {
            //   echo('<table class="table no-margin">');
            //   include(__DIR__."/../Partiels/ProfileOrderThead.phtml");
            //   foreach($order as $key=>$value)
            //   {
            //     include(__DIR__."/../Partiels/ProfileOrderList.phtml");
            //   }
            //   echo('</tbody></table>');
            //
            //   foreach($order as $key=>$value)
            //   {
            //       include(__DIR__."/../Partiels/DashboardOrderDetail.phtml");
            //   }
            //
            // }
            // else
            // {
            //   echo("<p>Aucune commande pour le moment</p>");
            // }
            ?>
          </div>

          <div class="tab-pane" id="profile" role="tabpanel">
            <form class="form-horizontal" action="<?= $requestUrl ?>/profil/updateuser" name="updateUser" method="post" enctype="multipart/form-data">

              <div class="form-group">
                <label for="inputName" class="col-sm-4 control-label">Nom</label>
                  <div class="col-sm-10">
                    <input type="text" name="lastName" class="form-control" id="inputName" value=<?php
                    if (isset($user['lastName']))
                    {
                      echo($user['lastName']);
                    }
                    else
                    {
                      echo("'Nom'");
                    }
                     ?>>
                </div>
              </div>

              <div class="form-group">
                <input type="hidden" name="mode" value="updateUser" />
                <label for="inputName" class="col-sm-4 control-label">Prénom</label>
                <div class="col-sm-10">
                  <input type="text" name="firstName" class="form-control" id="inputName" value=<?php
                  if (isset($user['firstName']))
                  {
                    echo("'".$user['firstName']."'");
                  }
                  else
                  {
                    echo("'Prénom'");
                  }
                   ?>>
                </div>
              </div>

              <div class="form-group">
                <label for="inputName" class="col-sm-4 control-label">Téléphone</label>
                <div class="col-sm-10">
                  <input type="text" name="phone" maxlength="10" class="form-control" id="inputName" value=<?php
                  if (isset($user['phone']))
                  {
                    echo("'".$user['phone']."'");
                  }
                  else
                  {
                    echo("+33");
                  }
                  ?>>
                </div>
              </div>

              <div class="form-group">
                <label for="inputEmail" class="col-sm-4 control-label">Email</label>
                <div class="col-sm-10">
                  <input type="email" name="mail" class="form-control" id="inputEmail" value=<?php
                  if (isset($user['mail']))
                  {
                    echo("'".$user['mail']."'");
                  }
                  else
                  {
                    echo("'adresse mail'");
                  }
                  ?>>
                </div>
              </div>

              <div class="form-group">
                <label for="exampleInputFile" class="col-sm-4 control-label">Avatar</label>
                <div class="col-sm-10">
                <input type="file" name="avatar" accept="image/*" id="exampleInputFile">
                <p class="help-block">Ajouter votre photo de profil ! (fichier images uniquement)</p>
              </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-resto101">Soumettre</button>
                </div>
              </div>
            </form>
          </div>

          <div class="tab-pane" id="passwd" role="tabpanel">
            <form class="form-horizontal" action="<?= $requestUrl ?>/profil/updateuser" name="updatePassword" method="post">
              <input type="hidden" name="mode" value="updatePassword" />
              <div class="form-group">
                <label for="inputName" class="col-sm-4 control-label">Ancien mot de passe</label>
                  <div class="col-sm-10">
                    <input type="text" name="oldPassword" class="form-control" id="inputName" placeholder="Votre ancien mot de passe">
                </div>
              </div>

              <div class="form-group">
                <label for="inputName" class="col-sm-4 control-label">Nouveau mot de passe</label>
                <div class="col-sm-10">
                  <input type="text" name="password" class="form-control" id="inputName" placeholder="Votre nouveau mot de passe">
                </div>
              </div>

              <div class="form-group">
                <label for="inputName" class="col-sm-4 control-label">Confirmer nouveau mot de passe</label>
                <div class="col-sm-10">
                  <input type="text" name="confirmPassword" class="form-control" id="inputName" placeholder="Retapez votre mot de passe">
                </div>
              </div>

              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-resto101">Soumettre</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
