
  <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">

<div class="form-group">
  <label for="inputTitle" class="col-sm-12 control-label">Nom</label>
    <div class="col-sm-12">
      <input required type="text" name="lastName" class="form-control col-sm-12" id="inputTitle">
  </div>
</div>

<div class="form-group">
  <label for="inputTitle" class="col-sm-12 control-label">Prénom</label>
    <div class="col-sm-12">
      <input required type="text" name="firstName" class="form-control col-sm-12" id="inputTitle">
  </div>
</div>

<div class="form-group">
  <label for="inputTitle" class="col-sm-12 control-label">Mail</label>
    <div class="col-sm-12">
      <input required type="text" name="mail" class="form-control col-sm-12" id="inputTitle">
  </div>
</div>

<div class="form-group">
  <label for="inputTitle" class="col-sm-12 control-label">Mot de passe</label>
    <div class="col-sm-12">
      <input required type="text" name="password" class="form-control col-sm-12" id="inputTitle">
  </div>
</div>

<div class="form-group">
  <label for="inputTitle" class="col-sm-12 control-label">Confirmer votre mot de passe</label>
    <div class="col-sm-12">
      <input required type="text" name="passwordControl" class="form-control col-sm-12" id="inputTitle">
  </div>
</div>

<div class="form-group">
  <label for="inputTitle" class="col-sm-12 control-label">Titre</label>
    <div class="col-sm-12">
      <button type="submit">S'inscrire</button>
  </div>
</div>

</form>
